---
- name: Update and Install Macbook Packages
  hosts: 127.0.0.1
  connection: local
  vars_prompt:
    - name: current_account_password
      prompt: What is your admin account password?
      private: true

  tasks:
    - name: Tap homebrew fonts
      community.general.homebrew_tap:
        name: homebrew/cask-fonts
    - name: Update homebrew formulae
      community.general.homebrew:
        state: latest
        update_homebrew: true
        upgrade_all: true
    - name: Upgrade all casks
      community.general.homebrew_cask:
        state: latest
        greedy: true
        upgrade_all: true
    - name: Install shells
      community.general.homebrew:
        name:
          - fish
          - fisher
          - starship
    - name: Install essential workflow tools
      community.general.homebrew:
        name:
          - bat
          - broot
          - btop
          - fd
          - fdupes
          - fzf
          - git
          - gh
          - lsd
          - p7zip
          - rename
          - ripgrep
          - shellcheck
          - yq
    - name: Install programming language tools
      community.general.homebrew:
        name:
          - rustup-init
          - volta
          - tfenv
          - shfmt
    - name: Install macosx utilities
      community.general.homebrew:
        name:
          - dockutil
          - m-cli
    - name: Install networking utilities
      community.general.homebrew:
        name:
          - httpie
          - nmap
    - name: Install tech stack utilities
      community.general.homebrew:
        name:
          - awscli
          - kubernetes-cli
          - stern
          - aws-es-proxy
    - name: Install other utilities
      community.general.homebrew:
        name:
          - ffmpeg
    - name: Install GUI applications
      community.general.homebrew_cask:
        sudo_password: '{{ current_account_password }}'
        name:
          - 1password
          - alfred
          - aws-vpn-client
          - calibre
          - docker
          - firefox
          - google-chrome
          - gpg-suite
          - intellij-idea
          - iterm2
          - kap
          - keka
          - kekaexternalhelper
          - lulu
          - slack
          - spotify
          - todoist
          - transmission
          - visual-studio-code
          - vlc
          - wireshark
          - zoom
          - font-fira-code-nerd-font
          - font-fira-mono-nerd-font
          - font-hack-nerd-font
          - lens
          - onyx
