# /etc/bashrc
# System-wide .bashrc file for interactive bash(1) shells.
# To enable the settings / commands in this file for login shells as well,
# this file has to be sourced in /etc/profile.

# If not running interactively, don't do anything
[ -z "$PS1" ] && return


############################# BASH Features ###################################
# checks the window size after each command and
# if necessary, updates the values of LINES and COLUMNS.
shopt -s checkwinsize
# save all lines of a multiple-line command in the same history entry.
shopt -s cmdhist
# replaces directory names with the results of word expansion.
shopt -s direxpand
# attempts spelling correction on directory names during word completion.
shopt -s dirspell
# includes filenames beginning with a ‘.’ in filename expansion.
shopt -s dotglob
# turn on ** matching all directories
shopt -s globstar

# Enable Bash Completion
if ! shopt -oq posix; then
 if [ -f /usr/share/bash-completion/bash_completion ]; then
   . /usr/share/bash-completion/bash_completion
 elif [ -f /etc/bash_completion ]; then
   . /etc/bash_completion
 fi
fi
############################# BASH Features ###################################


# System wide aliases and functions.

# Provides prompt for non-login shells, specifically shells started
# in the X environment. [Review the LFS archive thread titled
# PS1 Environment Variable for a great case study behind this script
# addendum.]

NORMAL="\[\e[0m\]"
RED="\[\e[1;31m\]"
GREEN="\[\e[1;32m\]"
if [[ $EUID == 0 ]] ; then
  PS1="$RED\u [ $NORMAL\w$RED ]# $NORMAL"
else
  PS1="$GREEN\u [ $NORMAL\w$GREEN ]\$ $NORMAL"
fi

unset RED GREEN NORMAL

# End /etc/bashrc